### ISSUE TITLE
authenticated failed and shared spatial anchor can't work

### ISSUE THREAD

**Issue by chris312319** [oculus-samples/Unity-SharedSpatialAnchors#21]
I have tried Unity-discover and everything works fine.
But I tried this with same app Id it always shows that authenticated failed and shared spatial anchor can't work
I have tried another app Id, it still works fine in Discover.
Is it the reason that SDK for this repostiry is too old?

**Comment by stephenm2022** [comment]
Hi @chris312319. I just grabbed a fresh clone of the repository and I was able to successfully authenticate. You might need to download the store build of your app first to enable the entitlement. After successful authentication with a store build, you can sideload apks from there.

Have you confirmed via logs that Platform SDK authentication is working for you in Discover when using the same app Id?

Let me know if the issue remains after trying the above.

**Comment by chris312319** [comment]
I have changed package name with my own company name, it works fine when I do same things in disocver.

And I haven't push Discover on to the store , is it necessary ? 

I have two app in my Oculus developer center now, and both of its id can work with Discover though.

**Comment by stephenm2022** [comment]
Most of the app features work in Discover without authentication. Have you confirmed that authentication is working via logs? The only feature that requires it is colocation (local multiplayer across two or more devices).

**Comment by chris312319** [comment]
Yes, here is my video with Disocer test, which shows the shared spatial anchors worked.
https://youtube.com/shorts/OwwHYl-NOPE?si=AmJyDf8xIzLdH1Uz

**Comment by stephenm2022** [comment]
Ok, thanks for confirming. Can you send me the logs from the SSA sample?

**Comment by chris312319** [comment]
Ok, I will post the logs here tomorrow.
Just log file in oculus 3 device?

**Comment by chris312319** [comment]
`12:21:12.369
OVRService
Unable to find AppId for package (com.Chris312319.ssaSample)
12:21:12.369
OVRService
com.oculus.horizon.service.ExternalPlatformLocal$PackageNotInLibraryException: Package com.Chris312319.ssaSample not in users library
12:21:12.369
OVRService
at com.oculus.horizon.service.ExternalPlatformLocal.getAppID(:537096024)
12:21:12.369
OVRService
at com.oculus.horizon.service.ExternalPlatformLocal.getAppID(:6)
12:21:12.369
OVRService
at com.oculus.horizon.service.OVRService$4.logToMarauder(:34)
12:21:12.369
OVRService
at com.oculus.aidl.OVRServiceInterface$Stub.onTransact(:124)
12:21:12.369
OVRService
at android.os.Binder.transact(Binder.java:1064)
12:21:12.369
OVRService
at com.facebook.secure.ktx.service.IdentityCheckingBinder.onTransact(:11)
12:21:12.369
OVRService
at android.os.Binder.execTransactInternal(Binder.java:1179)
12:21:12.369
OVRService
at android.os.Binder.execTransact(Binder.java:1143)`

Is this the reason?

**Comment by stephenm2022** [comment]
Hi @chris312319. Thanks for sharing your logs. Both apps seem to be failing entitlements and platform authentication. You will need to upload an apk to one of the store channels to test your apps end to end.

https://developer.oculus.com/documentation/unity/unity-platform-entitlements#build-and-upload-the-apk-file 

Discover will attempt to localize the spatial anchor even when platform authentication fails. If you are using the same account on two devices, it is likely that you will be able to localize the anchor without successfully sharing it.

**Comment by chris312319** [comment]
But there are two different accounts in two devices on the above video, but it still works?

I will try upload test app to the store, but I want to know the reason that Discover colocation can work.

**Comment by chris312319** [comment]
> Hi @chris312319. Thanks for sharing your logs. Both apps seem to be failing entitlements and platform authentication. You will need to upload an apk to one of the store channels to test your apps end to end.
> 
> https://developer.oculus.com/documentation/unity/unity-platform-entitlements#build-and-upload-the-apk-file
> 
> Discover will attempt to localize the spatial anchor even when platform authentication fails. If you are using the same account on two devices, it is likely that you will be able to localize the anchor without successfully sharing it.

I have add it to my beta channel then download from the beta page, but it still shows the autheicated failed, is it necessary to download it from server?

**Comment by chris312319** [comment]
> Hi @chris312319. Thanks for sharing your logs. Both apps seem to be failing entitlements and platform authentication. You will need to upload an apk to one of the store channels to test your apps end to end.
> 
> https://developer.oculus.com/documentation/unity/unity-platform-entitlements#build-and-upload-the-apk-file
> 
> Discover will attempt to localize the spatial anchor even when platform authentication fails. If you are using the same account on two devices, it is likely that you will be able to localize the anchor without successfully sharing it.

After upload and download by AppLab, authenticated failed won't appear at all.
But aonther question is that when I use any apply of anchors, it continuously popping "Saving anchor(s) failed.Retrying..." 
And if two people join colocation scene, it also happened.
And if entering Fast Colocation scene and create an anchor, it will shows that Saving anchors failed.Possible reasons include an unsupported device. 
But I am using Quest 3
